### ISSUE TITLE
无法加载图片

### ISSUE THREAD

**Issue by SENyiAi** [OpportunityLiu/ExViewer#178]
组件初始化失败。(Exception from HRESULT:0x88982F8B)

**Comment by OpportunityLiu** [comment]
哪个画廊

**Comment by SENyiAi** [comment]
ALL

**Comment by SENyiAi** [comment]
代理内出现大量puzaqhxrbn.hath.network:443连接

**Comment by OpportunityLiu** [comment]
看起来像是 webp 支持的问题，装一下 webp 插件试试
https://apps.microsoft.com/detail/9pg2dk419drg?hl=zh-CN&gl=US

**Comment by SENyiAi** [comment]
已修复，感谢
