### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by gareiz** [OpportunityLiu/ExViewer#39]
安装好后输入账号密码登陆显示
excep_fromhresult 0x80072EFD

**Comment by OpportunityLiu** [comment]
ERROR_INTERNET_CANNOT_CONNECT
12029
The attempt to connect to the server failed.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa385465(v=vs.85).aspx

错误代码是无法连接网络。
你确定网页版没问题？

**Comment by weiker** [comment]
同样的问题，没想到现在还有人开发win版的阅读器  支持！

**Comment by OpportunityLiu** [comment]
貌似是代理的问题，UWP应用走代理各种抽风，关掉VPN啥的试试

**Comment by gareiz** [comment]
晚上回去试试关了ss看行不行

**Comment by weiker** [comment]
不开代理不报错  但是连不上网站啊

**Comment by gareiz** [comment]
@weiker 不翻墙可以登录并且加载内容，但是加载速度比起浏览器不开代理访问网站慢很多

**Comment by OpportunityLiu** [comment]
登陆以后应该就没问题了，主要是登陆那块有点抽风

但我挂着代理也能正常登陆，具体原因还需要调查

**Comment by OpportunityLiu** [comment]
由于e站改用recaptcha v2，登录方式已改为使用WebView从网页登录，问题失效

**Comment by OpportunityLiu** [comment]
试一下这个工具？
[EnableLoopback.zip](https://github.com/OpportunityLiu/ExViewer/files/1811176/EnableLoopback.zip)
