### ISSUE TITLE
希望加快预载速度

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [OpportunityLiu/ExViewer#40]
载入太慢了，撸着撸着还得停下来等载入。

**Comment by OpportunityLiu** [comment]
网太渣怪我咯 😿 

在 **设置 > 连结** 里把 **始终加载压缩的图片** 打开试试

**Comment by zzzop** [comment]
> 网太渣怪我咯 😿
> 
> 在 **设置 > 连接** 里把 **始终加载压缩的图片** 打开试试

请问软件会预载后面的几页内容呢，如果有设置的地方就更好了
