### ISSUE TITLE
Missing sourcefiles preventing compilation

### ISSUE THREAD

**Issue by PBXg33k** [OpportunityLiu/ExViewer#42]
Hi,

I tried to fork your project in order to add some features i would personally love to use, but i am unable to compile the project because two files are missing from source control.

<img width="359" alt="missing-files" src="https://user-images.githubusercontent.com/1777196/29430685-9f24a684-8395-11e7-940b-6cf2281e95ef.PNG">

**Comment by OpportunityLiu** [comment]
After restore package, run `Convert-Resource` to generate these files.

See: https://github.com/OpportunityLiu/ResourceGenerator
