### ISSUE TITLE
导出功能没有了吗？

### ISSUE THREAD

**Issue by inberitor** [OpportunityLiu/ExViewer#43]
导出功能找不到了

**Comment by OpportunityLiu** [comment]
因为现在的存储方式改为SHA1做文件名，然后堆在一起放，所以之前的导出功能失效了，新的还没做

**Comment by OpportunityLiu** [comment]
如果导出单个文件的话，可以直接打开图片，选择 共享-复制到剪贴板，然后粘贴到导出文件夹

**Comment by OpportunityLiu** [comment]
在新版本中加回来了
打开画廊，选择“共享-复制到剪贴板”，然后粘贴到导出文件夹

**Comment by inberitor** [comment]
感谢

**Comment by inberitor** [comment]
移动端共享会闪退

**Comment by OpportunityLiu** [comment]
系统版本？

**Comment by inberitor** [comment]
1703

**Comment by OpportunityLiu** [comment]
我这边也出现了，桌面版也有同样的情况，但是在 DEBUG 模式下没有问题，感觉又是。net native的锅。。。
先凑合用吧，等1709出了再看看吧

**Comment by OpportunityLiu** [comment]
再更新一下试试，应该修复了

**Comment by inberitor** [comment]
PC端是可以了，然而移动端的共享并没有复制粘贴这种东西，sorry

**Comment by OpportunityLiu** [comment]
不想改了，你下个8zip之类的，然后分享过去吧

**Comment by OpportunityLiu** [comment]
8zip是会自动打包成一个压缩文件的

**Comment by inberitor** [comment]
可以了，感谢
