### ISSUE TITLE
初次登录问题，卡在验证码刷新

### ISSUE THREAD

**Issue by Yanzyboy15** [OpportunityLiu/ExViewer#45]
![default](https://user-images.githubusercontent.com/31788374/30237150-678b713c-955e-11e7-89bf-bf072c881ebe.png)如图，我是第一次使用E-viewer登录Ex站，感觉UWP版还是挺值得支持一下的，但是登录界面无限卡在验证码刷新，验证码一片黑，请问如何处理？

**Comment by OpportunityLiu** [comment]
显示不了验证码是因为 e 站使用的是 Google 的 recapcha 验证码，所以需要科学上网才能载入验证码。

但是前几次登录的话，其实是不需要验证码的，所以可以空着

**Comment by OpportunityLiu** [comment]
由于e站改用recaptcha v2，登录方式已改为使用WebView从网页登录，问题失效
