### ISSUE TITLE
希望您能开发移动版本

### ISSUE THREAD

**Issue by dengbohan** [OpportunityLiu/ExViewer#47]
软件很棒，如果有移动版就更好了

**Comment by OpportunityLiu** [comment]
这是uwp，有wp版的。。

**Comment by dengbohan** [comment]
能贴一下链接吗？谢谢

**Comment by OpportunityLiu** [comment]
https://github.com/OpportunityLiu/ExViewer/releases
Downloads里选`*_ARM.appx`就是啊
https://github.com/OpportunityLiu/ExViewer/wiki/安装说明
我觉得我wiki也写的很清楚了
