### ISSUE TITLE
为什么不上架商店呢？

### ISSUE THREAD

**Issue by cmpute** [OpportunityLiu/ExViewer#50]
安装太麻烦了

**Comment by OpportunityLiu** [comment]
上不了，实在懒得搞个壳去骗商店审核人员了
> Content Policies: 11.7 Adult Content - In-App
>
>Your app must not contain or display content that a reasonable person would consider pornographic or sexually explicit.

**Comment by cmpute** [comment]
连设置成18+就不能上商店的吗？商店原来这么严？

**Comment by g-aghayev** [comment]
[winget 仓库](https://github.com/microsoft/winget-pkgs/pull/4996)不限制 `pornographic or sexually explicit`
但是安装证书太麻烦了
