### ISSUE TITLE
显示不了图片

### ISSUE THREAD

**Issue by Alu00** [OpportunityLiu/ExViewer#51]
![wp_ss_20180210_0001](https://user-images.githubusercontent.com/28616314/36057757-b9e13e68-0e4d-11e8-81f9-d04c367c6c5c.png)
一直这样

**Comment by OpportunityLiu** [comment]
E站的设置更新了

临时的解决办法是用网页版上 https://e-hentai.org/uconfig.php 和 https://exhentai.org/uconfig.php

![image](https://user-images.githubusercontent.com/13471233/36060289-90aae2ae-0e81-11e8-9cca-4ed838538f26.png)
![image](https://user-images.githubusercontent.com/13471233/36060293-99c83e22-0e81-11e8-9e98-2af3f16dd384.png)
这两项这样选择，点击 Apply，然后再使用应用。

**Comment by Alu00** [comment]
可以了

**Comment by OpportunityLiu** [comment]
最新版本已经修复此问题
https://github.com/OpportunityLiu/ExViewer/releases/tag/v2018.2.14
