### ISSUE TITLE
無法在2018年3月17日後安裝程式

### ISSUE THREAD

**Issue by nekokonkagaya** [OpportunityLiu/ExViewer#53]
看了一下應該是證書過期(到期日:2018年3月17日)所導致的，請問能夠跟進嗎?

**Comment by OpportunityLiu** [comment]
有除了换证书以外的办法吗

**Comment by OpportunityLiu** [comment]
https://github.com/OpportunityLiu/ExViewer/releases/tag/v2018.3.21
姑且换了证书，估计要卸载以后重装

**Comment by nekokonkagaya** [comment]
手機完全卸载舊版，安裝新證書之後和已經可以安裝新版本程式(v2018.3.21)了。
