### ISSUE TITLE
重装最新版本后404

### ISSUE THREAD

**Issue by MichaelMai2000** [OpportunityLiu/ExViewer#54]
之前使用ExViewer_2017.9.15.0_x64版本，
卸载重装ExViewer_2018.3.21.0_x86_x64_arm版本后，首次登录，登录界面遇到
`
404 (NotFound) 
https://forums.e-hentai.org/index.php?act=Login 
`
已确认使用全局代理，
浏览器可以通过代理正常登录，
Windows10。

**Comment by OpportunityLiu** [comment]
#39 
需要对UWP启用代理

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/37863439-59a237ec-2f99-11e8-81b5-893921ced568.png)
1. Exempt none
1. Save changes
1. Exempt all
1. Save changes

**Comment by MichaelMai2000** [comment]
问题解决了。
