### ISSUE TITLE
证书怎么只有一天时限。。

### ISSUE THREAD

**Issue by zyl550** [OpportunityLiu/ExViewer#57]
3.17-3.18

**Comment by OpportunityLiu** [comment]
？
![image](https://user-images.githubusercontent.com/13471233/38184700-0df316ce-367c-11e8-8830-85b267581d27.png)

**Comment by zyl550** [comment]
看错了。。不过还是安装不了，所以以为是证书过期了


![image](https://user-images.githubusercontent.com/6858108/38185649-c7d60cf4-3681-11e8-992f-61004652ba26.png)

**Comment by zyl550** [comment]
等等。。没看错。。我的怎么是2017年到2018年的。。

![image](https://user-images.githubusercontent.com/6858108/38185684-ed6a1cb2-3681-11e8-9e17-56f87afa42fc.png)

**Comment by OpportunityLiu** [comment]
去下最新版本。。。
测试证书只能有1年的有效期

**Comment by zyl550** [comment]
添加到信任还是不可以。。是不是要把这几个移出去

![image](https://user-images.githubusercontent.com/6858108/38186371-515b64f8-3685-11e8-8185-6efa8e51338e.png)

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/38188600-324b2832-368f-11e8-9d06-ae7e5483301c.png)
https://github.com/OpportunityLiu/ExViewer/wiki/安装说明#%E5%AE%89%E8%A3%85%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6
