### ISSUE TITLE
非代理情况下无法加载画廊和其他异常

### ISSUE THREAD

**Issue by MichaelMai2000** [OpportunityLiu/ExViewer#58]
1. Windows 10，无全局代理，浏览器直接连接 https://ex **能正常访问**。
客户端ExViewer_2018.3.21.0_x86_x64_arm版本，配合EnableLoopback并开启代理，首次登录成功。
去掉（Exempt none）EnableLoopback、关闭代理后，可以进入程序，但**无法加载**画廊；同时出现以下错误
![image](https://user-images.githubusercontent.com/10582944/38351283-64c00798-38e1-11e8-8c66-603bd534ad9b.png)

2. 配额显示与账户本身不符：
![image](https://user-images.githubusercontent.com/10582944/38351333-8700fc22-38e1-11e8-8243-bc8ff411bf60.png)
![image](https://user-images.githubusercontent.com/10582944/38351370-b1fb9dc4-38e1-11e8-895d-d7381ce7f6a2.png)

[关于第二个问题可能有用的情报：](https://github.com/kayanouriko/E-HentaiViewer)
> 网站设置页面(uconfig.php)更新了...
>所以app上的高级设置暂时全部失效了,不用再邮件我啦,我已经知道这事了...

**Comment by OpportunityLiu** [comment]
1. 确认切换到ex了？我这边不能复现问题。
![image](https://user-images.githubusercontent.com/13471233/38352590-54633ca8-38e6-11e8-9295-0c2059a94628.png)
2. e-h被墙了，ex没事，配额信息来自 https://e-hentai.org/home.php 的，被墙了就显示默认的数字

**Comment by OpportunityLiu** [comment]
PS：设置页面更新的问题 https://github.com/OpportunityLiu/ExViewer/releases/tag/v2018.2.14 就已经跟进了，更新说明第三条说的就是这个

**Comment by MichaelMai2000** [comment]
我的锅，这个开关。。。[捂脸]
谢谢。

**Comment by MichaelMai2000** [comment]
> e-h被墙了，ex没事
这个我理解，但是收藏在ex里面也有，但是客户端加载不出来。。。。。。

**Comment by MichaelMai2000** [comment]
然后很慢的收藏也加载出来了。。。

**Comment by OpportunityLiu** [comment]
看来问题解决了
