### ISSUE TITLE
最新版无法使用水平滚动

### ISSUE THREAD

**Issue by a545774001** [OpportunityLiu/ExViewer#59]
如题，使用水平滚动时打开任何一页都会返回第一页且无法滚动，垂直滚动正常，老版本没有这个问题。

**Comment by OpportunityLiu** [comment]
是移动版吗？
貌似 WP 确实有这个bug，导致无法在运行中切换滚动方向。
不要选择“仅对 webtoon 应用垂直滚动”，选定滚动方向以后重启应用

**Comment by a545774001** [comment]
问题应该解决了，谢谢
