### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by time937** [OpportunityLiu/ExViewer#71]
为什么安装时一直说“应用安装失败,错误消息: 系统找不到指定的文件。 (0x80070002)”呢？吐血

**Comment by OpportunityLiu** [comment]
感觉像是搞了什么优化删了系统文件的样子

**Comment by time937** [comment]
今天突然又安装成功了，明明我什么也没做。。只是登录界面一直显示404，开了魔法上网用网页能上去ehentai，但软件打开还是404。

**Comment by OpportunityLiu** [comment]
https://github.com/OpportunityLiu/ExViewer/wiki/解决连接问题

**Comment by time937** [comment]
ＨＳＯ

**Comment by OpportunityLiu** [comment]
？

**Comment by time937** [comment]
好色哦，谢谢大佬。
