### ISSUE TITLE
为什么登录之后无法进入软件呢？

### ISSUE THREAD

**Issue by yaodao0yaodao** [OpportunityLiu/ExViewer#82]
已经登录成功了，登录完成后显示这个界面
![default](https://user-images.githubusercontent.com/20895333/42737528-2883fdaa-88a7-11e8-8ea5-dfc3c3d775e0.PNG)
却无法进入软件
因为改hosts uwp不生效
我在路由器改的自定义DNS解析
是跟这个有关么？

**Comment by yaodao0yaodao** [comment]
解决了，再翻墙就好了

**Comment by Moreki** [comment]
![图片](https://user-images.githubusercontent.com/14026143/60379641-12d98680-9a69-11e9-9d00-f6a577df2b64.png)
不知道再翻是什么意思，我一直卡在这个已登录界面了。

**Comment by Moreki** [comment]
![无标题](https://user-images.githubusercontent.com/14026143/60379791-a01dda80-9a6b-11e9-8d09-7415ed7ec2cd.png)
我也是同样问题，但不知道重新翻墙具体是什么步骤，故还卡在已登录界面。

**Comment by OpportunityLiu** [comment]
复现不了，你关了重开一下

**Comment by Moreki** [comment]
试过了，找不到头绪。
因为一直这样所以我没在电脑上用，手机上倒是登陆后就直接跳转到应用首页了。

**Comment by Moreki** [comment]
奇怪之处是首次打开应用后输入用户名密码后登录，网页显示的还是游客，然后再次登录就出现上述截图的样子了。
手机上这一步操作是正常的。
