### ISSUE TITLE
好东西，如何记录最后看到的页码？

### ISSUE THREAD

**Issue by TommyWOo82** [OpportunityLiu/ExViewer#84]
比如，一个，200页的，我看到一半，退出来再进，还可以看到最后的进度。可是关app再进，就没了。。是我操作方式不对吗？多谢

**Comment by OpportunityLiu** [comment]
操作方式没问题，你说的功能正在规划中，最近没时间做

**Comment by OpportunityLiu** [comment]
现在可以通过历史纪录功能找到最后浏览的记录了

**Comment by OpportunityLiu** [comment]
如果还有其他想法可以随时 Reopen 或提新的 Issue
